version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agendamento_postgres
    environment:
      POSTGRES_DB: agendamento_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agendamento_network

  redis:
    image: redis:7-alpine
    container_name: agendamento_redis
    ports:
      - "6379:6379"
    networks:
      - agendamento_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agendamento_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/agendamento_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - agendamento_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agendamento_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - agendamento_network

volumes:
  postgres_data:

networks:
  agendamento_network:
    driver: bridge
